### PR TITLE
get_bio_fmt_specimens improvements

### PR DESCRIPTION
**Pull request by TransGirlCodes**

### CODE REVIEW

**Comment by jgreener64** [comment]
Looks good to me :+1:

**Comment by TransGirlCodes** [comment]
Actually I've just seen a blog post about DataDeps.jl, if it's applicable to this problem I might try it out instead. I'll have a go and report back.

**Comment by jgreener64** [comment]
Sure, though we should avoid over-engineering what is just the download of a few files.

**Comment by TransGirlCodes** [comment]
Ok, I think this is ready. This provides slightly more conveinience for testing. You can use `bio_fmt_specimens("FASTA", (x) -> x["valid"])` for example, to get all the paths for the FASTA specimens which are valid examples of the format. So no DataDeps or over engineering, but a bit more conveinience in the function(s) now.

**Comment by jgreener64** [comment]
Nice one.

**Comment by jgreener64** [comment]
@Ward9250 would you be able to bump the BioCore version to include this change in the release? Thanks.

**Comment by TransGirlCodes** [comment]
@jgreener64 Sure would! I was just waiting to see how the docs generate before taggin the release - but then it was lunch 🍰.

**Comment by TransGirlCodes** [comment]
@jgreener64 Ok I've tagged the release, hang in there for METADATA.jl to do its thing.

**Pull request merged**
