### PR TITLE
[RTR]: Update get_fmt_specimens method

### PR DESCRIPTION
**Pull request by TransGirlCodes**
Updates the method for fetching specimens from the BioFmtSpecimens repository.

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
This is required since fetching the specimens is failing for GeneticVariation.jl, the default commit number of the method was not recognised.

**Comment by bicycle1885** [comment]
This is not directly related to your change but I guess `git clone --depth 1` is not a reliable way to check out an arbitrary commit.

**Comment by TransGirlCodes** [comment]
@bicycle1885 We can instead just clone the repository and then either A). Checkout the commit hash, or B). Do a hard reset to the commit hash?

**Comment by bicycle1885** [comment]
I think (A) would work. Also, it would be better to pull the master branch before checkout.

**Comment by tkelman** [comment]
Yep, should probably remove the `--depth 1` and add a `git fetch origin` or something like that

**Comment by TransGirlCodes** [comment]
This is ready to merge, but I'm wondering, would people perhaps like it if BioFmtSpecimens had version tags, and can pull a specific version for their tests? If so maybe it will be a separate PR, as this needs fixing quickly for other packages.

**Pull request merged**
